<?php

return [
    'checks' => [
        'comment' => 'Comente',
        'item' => 'Item',
        'php_required' => ':version ou mais nova requerida',
        'status' => 'Estado',
        'title' => 'Checagem Pré-Instalação',
    ],
    'database' => [
        'credentials' => 'Credenciais do Banco de Dados',
        'host' => 'Servidor',
        'host_placeholder' => 'Use localhost para Unix-Socket',
        'name' => 'Nome do Banco de Dados',
        'password' => 'Senha',
        'port' => 'Porta',
        'port_placeholder' => 'Deixe vazio se estiver usando Unix-Socket',
        'socket' => 'Unix-Socket',
        'socket_placeholder' => 'Use apenas para caminho de socket personalizado',
        'test' => 'Verificar credenciais',
        'title' => 'Configure o Banco de Dados',
        'username' => 'Usuário',
    ],
    'finish' => [
        'config_exists' => 'arquivo config.php existe',
        'config_not_required' => 'Este arquivo não é exigido. Aqui está o padrão.',
        'config_not_written' => 'Não pode escrever em config.php',
        'config_written' => 'arquivo config.php gravado',
        'copied' => 'Copiado para área de transferência',
        'env_manual' => 'Atualizar manualmente o arquivo :file com o seguinte conteúdo',
        'env_not_written' => 'Não pode escrever o arquivo .env',
        'env_written' => 'arquivo .env gravado',
        'manual_copy' => 'Pressione Ctrl-C para copiar',
        'not_finished' => 'Você ainda não terminou!',
        'retry' => 'Tentar novamente',
        'statistics' => 'Seria ótimo se você considerasse contribuir para nossas estatísticas, você pode fazer isso em :about e marcar a caixa em Estatísticas.',
        'statistics_link' => 'Página sobre o LibreNMS',
        'thanks' => 'Obrigado por configurar o LibreNMS.',
        'title' => 'Fim da instalação',
        'validate' => 'Primeiro, você precisa :validate e corrigir todos os erros.',
        'validate_link' => 'validar sua instalação',
    ],
    'install' => 'Instalação',
    'migrate' => [
        'building_interrupt' => 'Não feche esta página nem interrompa a importação!',
        'error' => 'Erro encontrado, verifique a saída para obter detalhes.',
        'migrate' => 'Construindo o Banco de Dados',
        'retry' => 'Tentar novamente',
        'timeout' => 'A solicitação HTTP expirou, sua estrutura de banco de dados pode estar inconsistente.',
        'wait' => 'Por favor, aguarde...',
    ],
    'steps' => [
        'checks' => 'Verificações de pré-instalação',
        'database' => 'Banco de Dados',
        'finish' => 'Concluir instalação',
        'migrate' => 'Construir Banco de Dados',
        'user' => 'Criar Usuário',
    ],
    'title' => 'Instalação do LibreNMS',
    'user' => [
        'button' => 'Adicionar Usuário',
        'created' => 'Criar usuário',
        'email' => 'Email',
        'failure' => 'Falha ao criar usuário',
        'password' => 'Senha',
        'success' => 'Sucesso ao criar o usuário',
        'title' => 'Criar usuário administrador',
        'username' => 'Usuário',
    ],
];
